# Generated by Django 4.2.4 on 2023-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_migration_price_category_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
